spring.mvc.throw-exception-if-no-handler-found: true
spring.resources.add-mappings: true

spring.datasource.url: jdbc:mysql://localhost:3306/blog
spring.datasource.username: root
spring.datasource.password: testmysql
#spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.hibernate.ddl-auto: none
spring.jpa.show-sql: true
server.port: 8081

#spring.datasource.initialization-mode: always
spring.datasource.initialization-mode: never

spring.data.web.pageable.page-parameter: offset
spring.data.web.pageable.size-parameter: limit

init.title: DevPub
init.subtitle: Рассказы разработчиков
init.phone: +7 903 666-44-55
init.email: mail@mail.ru
init.copyright: Дмитрий Сергеев
init.copyrightFrom: 2005

time.expired.mc: 3600000
restore.code.expired.hours: 48

#spring.servlet.multipart.max-file-size: 256KB
#spring.servlet.multipart.max-request-size: 256KB

resources.path: ./src/main/resources
upload.path: /upload
avatar.path: /avatars
max.file.size: 256000
max.photo.size: 5000

spring.mail.host: smtp.inbox.ru
spring.mail.fromEmail: daniilshipilov@inbox.ru
spring.mail.password: Hp9Bd47dqT
spring.mail.port: 465
spring.mail.protocol: smtps
spring.mail.properties.mail.smtp.auth: true
spring.mail.debug: false

root.url.path: "http://localhost:8081"

