insert into posts
(is_active, moderation_status, text, time, title, view_count, user_id, moderator_id)
values
(1, 'DECLINED', 'We can modify the state of the database also with a native query. We just need to add the @Modifying annotation: We can modify the state of the database also with a native query. We just need to add the @Modifying annotation: We can modify the state of the database also with a native query. We just need to add the @Modifying annotation:', '2021-07-21 12:50:00', "18 The database also with a native query", 1, 1, 1),
(1, 'DECLINED', 'Often, well encounter the need for building SQL statements based on conditions or data sets whose values are only known at runtime. And in those cases, we cant just use a static query.', '2021-07-14 19:27:00', "19 We cant just use a static query", 1, 2, 1),
(1, 'NEW', 'Предположим, вы решили, что работа по проблеме #53 закончена и её можно влить в ветку master. Для этого нужно выполнить слияние ветки iss53 точно так же, как вы делали это с веткой hotfix ранее. Все, что нужно сделать переключиться на ветку, в которую вы хотите включить изменения, и выполнить команду git merge:', '2021-07-22 07:55:45', "20 И выполнить команду git merge", 1, 1, 1),
(1, 'NEW', 'Writing migrations manually takes a lot of time; instead, we can generate them based on our JPA entities. We can achieve this using a plugin for IntelliJ IDEA called JPA Buddy. Writing migrations manually takes a lot of time; instead, we can generate them based on our JPA entities. We can achieve this using a plugin for IntelliJ IDEA called JPA Buddy.', '2021-07-12 07:55:45', "21 Writing migrations manually takes a lot of time", 1, 2, 1),
(0, 'NEW', 'Предположим, вы решили, что работа по проблеме #53 закончена и её можно влить в ветку master. Для этого нужно выполнить слияние ветки iss53 точно так же, как вы делали это с веткой hotfix ранее. Все, что нужно сделать переключиться на ветку, в которую вы хотите включить изменения, и выполнить команду git merge:', '2021-07-22 07:55:45', "22 И выполнить команду git merge", 1, 1, 1),
(0, 'NEW', 'Writing migrations manually takes a lot of time; instead, we can generate them based on our JPA entities. We can achieve this using a plugin for IntelliJ IDEA called JPA Buddy. Writing migrations manually takes a lot of time; instead, we can generate them based on our JPA entities. We can achieve this using a plugin for IntelliJ IDEA called JPA Buddy.', '2021-07-12 07:55:45', "23 Writing migrations manually takes a lot of time", 1, 2, 1);
